file.choose()
sites<-read.csv2(file="\\\\eir.uib.no\\home6\\ial008\\FunCab\\Data\\Vegetation data\\main - Copy1.csv", dec = ".")
names(sites)
str(sites)
plot(sites$temp, sites$total.l)
sites_all<-read.csv2(file="\\\\eir.uib.no\\home6\\ial008\\FunCab\\Data\\Vegetation data\\Data (2).csv",  dec = ".")
sites_all<-read.csv2(file="\\\\eir.uib.no\\home6\\ial008\\FunCab\\Data\\Vegetation data\\sites_all.csv", dec = ".")
cor(sites_all$temp, sites_all$bryophytes)
plot(sites_all$TEMP, sites_all$GRAMINOIDS)
pairs(sites_all, gap=0)
lines(pairs(sites_all, gap=0))
pairs(sites, gap=0)
cor.test(sites_all$temp, sites$forbs)
cor.test(sites$temp, sites$graminoids)
cor.test(sites$temp, sites$bryophytes)
cor.test(sites$temp, sites$litter)
cor.test(sites$temp, sites$total.l)
cor.test(sites$temp, sites$total.l.1)
cor.test(sites$prec, sites$forbs)
cor.test(sites$prec, sites$graminoids)
cor.test(sites$prec, sites$bryophytes)
cor.test(sites$prec, sites$litter)
cor.test(sites$prec, sites$total.l)
cor.test(sites$prec, sites$total.l.1)
boxplot(sites_all$BIOMASS)
cor(sites_all$TEMP, sites_all$FORBS)
cor.test(sites_all$TEMP, sites_all$FORBS)
cor.test(sites_all$TEMP, sites_all$GRAMINOIDS)
cor.test(sites_all$TEMP, sites_all$BRYOPHYTES)
cor.test(sites_all$TEMP, sites_all$LITTER)
cor.test(sites_all$PREC, sites_all$FORBS)
cor.test(sites_all$PREC, sites_all$GRAMINOIDS)
cor.test(sites_all$PREC, sites_all$BRYOPHYTES)
cor.test(sites_all$PREC, sites_all$LITTER)
plot(sites_all$TEMP, sites_all$FORBS)

library(car)
fit <- lm(sites_all$TEMP~sites_all$GRAMINOIDS+sites_all$LITTER)
outlierTest(fit)
qqPlot(fit, main="QQ Plot")
abline(sites_all$TEMP, sites_all$FORBS)
abline(lm(sites_all$TEMP, sites_all$FORBS))
plot(TEMP,FORBS,main=paste("Cor = ",round(cor(TEMP~FORBS),3)))
hist(sites_all$FORBS)
hist(sites_all$FORBS_t)
scatterplot(BRYO_t~PREC | site, reg.line=lm, smooth=FALSE, spread=FALSE, id.method='mahal', id.n = 2, boxplots=FALSE, span=0.5, by.groups=FALSE, data=sites_all)
scatterplot(sites_all$PREC, sites_all$GRAM_t, reg.line = lm)
pairs(sites_all, line.main=1)
cor.test(sites_all$BIOMASS, sites_all$LITTER_t)
scatter.smooth(sites_all$BIOMASS, sites_all$LITTER_t, xlab = "BIOMASS", ylab = "LITTER")
dif.yrs<-read.csv2(file="C:/Users/Terezie/Desktop/UiB school stuff/Bio299/statistics/total3.csv")
cor.test(dif.yrs$bryophytes.2013, dif.yrs$bryophytes.2015)
cor.test(dif.yrs$vascular.plants.2013, dif.yrs$vascular.plants.2015)
cor.test(dif.yrs$total.biomass.2013, dif.yrs$total.biomass.2015)

